name: Bump Version

on:
  pull_request:
    types: [closed]

jobs:
  bump_version:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT_IPR_TOKEN_ACTION }}

    - name: Setup git
      run: |
        git config --global user.email "iprafols@users.noreply.github.com"
        git config --global user.name "Ignasi Pérez-Ràfols (bot)"
    
    - name: Set up Python
      uses: actions/setup-python@v4
      
    - name: Install bump2version
      run: pip install bump2version
            
    - name: Increase patch
      if: ${{ always() && !contains(github.event.pull_request.labels.*.name, '[bump major]') && !contains(github.event.pull_request.labels.*.name, '[bump minor]') && !contains(github.event.pull_request.labels.*.name, '[no bump]') }}
      run: bump2version patch --verbose
      
    - name: Bump major version
      if: ${{ always() && contains(github.event.pull_request.labels.*.name, '[bump major]') }}
      run: bump2version major --verbose --tag
      
    - name: Bump minor version
      if: ${{ always() && contains(github.event.pull_request.labels.*.name, '[bump minor]') }}
      run: bump2version minor --verbose --tag
      
    - name: No version bump
      if: ${{ always() && contains(github.event.pull_request.labels.*.name, '[no bump]') }}
      run: echo "No version bump requested"
      
    - name: Push changes
      if: ${{ always() && !contains(github.event.pull_request.labels.*.name, '[no bump]') }}
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_IPR_TOKEN_ACTION }}
        tags: true
        commit_message: "Bump version: {current_version} → {new_version} [skip ci]"